#!/bin/bash

UUID=$1

if [ ! -z "$UUID" ]
then

  UUID_LINK="/dev/disk/by-uuid/$UUID"

  if [ -L $UUID_LINK ]
  then

    if sudo /bin/umount $UUID_LINK
    then
      DEST=/media/$UUID
      sudo /bin/rmdir $DEST
      sudo /bin/sed -i "/$UUID/d" /etc/fstab
      echo "true"
    else
      echo "false"
    fi
  else
    echo "false"
  fi
else
  echo "false"
fi

echo $STATUS
