#!/bin/bash
### BEGIN INIT INFO
# Provides:          nasadmin 
# Required-Start:    
# Required-Stop: 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6 
### END INIT INFO

source /etc/default/nasadmin

NASD="/usr/bin/nasadmin"
ROOT=/usr/share/nasadmin/web

OPTIONS="-p $PORT -I $CGI -r $ROOT -u www-data"

# Check for daemon presence
[ -x "$NASD" ] || exit 0

case "$1" in
  start)
    echo "Starting NASAdmin service..."
    start-stop-daemon --start --quiet --oknodo --background --exec "$NASD" -- $OPTIONS
    ;;
  stop)
    echo "Stopping NASAdmin service..."
    start-stop-daemon --stop --quiet --oknodo --retry 2 --exec "$NASD"
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    status_of_proc "$NASD" nasadmin 
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/nasadmin {start|stop|restart|reload|force-reload|status}"
    exit 1
esac

